database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite:veganrealm.db
  properties:
    charSet: UTF-8
    foreign_keys: true
views:
  freemarker:
    strict_syntax: true
  mustache:
    cache: false
